import React, { useState } from 'react';
import { AnalysisResult } from '../types/analysis';
import { RiskGauge } from './RiskGauge';
import { ShieldCheck, ShieldAlert, AlertTriangle, Cpu, Radio, AlertCircle, ChevronDown, ChevronUp, RefreshCw, FileText, CheckCircle2, Activity } from 'lucide-react';

interface ResultCardProps {
  result: AnalysisResult;
  onReset?: () => void;
}

export const ResultCard: React.FC<ResultCardProps> = ({ result, onReset }) => {
  const [showTechnical, setShowTechnical] = useState<boolean>(false);

  const isSpoof = result.status === 'SUSPICIOUS' || result.status === 'HIGH_RISK';

  const getVerdictLabel = () => {
    if (result.status === 'SAFE') return 'SAFE';
    return 'SPOOF SUSPECTED';
  };

  const getVerdictBadgeClass = () => {
    if (result.status === 'SAFE') {
      return 'bg-emerald-950/90 border-emerald-500/50 text-emerald-400';
    }
    if (result.status === 'SUSPICIOUS') {
      return 'bg-amber-950/90 border-amber-500/50 text-amber-400';
    }
    return 'bg-rose-950/90 border-rose-500/50 text-rose-400';
  };

  return (
    <div className="bg-slate-900/80 rounded-2xl p-6 sm:p-8 border border-slate-800 space-y-6">
      
      {/* Mode Banner */}
      {result.isDemo && (
        <div className="p-3 rounded-xl bg-amber-950/80 border border-amber-500/40 text-amber-300 text-xs font-semibold flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
            <span>DEMO SAMPLES — Offline demonstration sample (Not a live security analysis)</span>
          </div>
        </div>
      )}

      {/* 1. Primary Security Verdict Block */}
      <div className="flex flex-col md:flex-row items-center justify-between p-6 bg-slate-950/80 rounded-2xl border border-slate-800 gap-6">
        <div className="space-y-2 text-center md:text-left">
          <span className="text-[11px] uppercase tracking-widest font-extrabold text-slate-400 block">
            SECURITY VERDICT
          </span>
          <div className={`inline-flex items-center space-x-2 px-5 py-2 rounded-full border font-black text-xl tracking-wider ${getVerdictBadgeClass()}`}>
            {result.status === 'SAFE' ? (
              <ShieldCheck className="w-6 h-6 text-emerald-400" />
            ) : (
              <ShieldAlert className="w-6 h-6" />
            )}
            <span>{getVerdictLabel()}</span>
          </div>
          <p className="text-xs text-slate-400 pt-1">
            Official evaluation generated by VoxShield Neural & DSP Engine
          </p>
        </div>

        {/* Risk Score & Gauge */}
        <div className="flex flex-col items-center justify-center px-6 py-3 bg-slate-900/90 rounded-xl border border-slate-800 shrink-0">
          <RiskGauge score={result.risk_score} status={result.status} />
          <div className="mt-2 text-center">
            <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider block">Risk Score</span>
            <span className="text-xl font-mono font-bold text-white">{result.risk_score}</span>
          </div>
        </div>
      </div>

      {/* 2. Detection Signals Section */}
      <div className="bg-slate-950/60 rounded-xl p-5 border border-slate-800/80 space-y-4">
        <h4 className="text-xs uppercase font-extrabold tracking-widest text-slate-300 flex items-center space-x-2">
          <Activity className="w-4 h-4 text-cyan-400" />
          <span>DETECTION SIGNALS</span>
        </h4>

        <div className="space-y-3">
          
          {/* Synthetic Voice Signal */}
          <div className="space-y-1">
            <div className="flex items-center justify-between text-xs">
              <span className="text-slate-300 font-medium">Synthetic Voice</span>
              <span className="font-mono font-bold text-cyan-400">
                {(result.synthetic_score * 100).toFixed(1)}%
              </span>
            </div>
            <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-800">
              <div
                className="h-full bg-cyan-500 transition-all duration-500"
                style={{ width: `${Math.max(2, result.synthetic_score * 100)}%` }}
              />
            </div>
          </div>

          {/* Replay Attack Signal */}
          <div className="space-y-1">
            <div className="flex items-center justify-between text-xs">
              <span className="text-slate-300 font-medium">Replay Attack</span>
              <span className="font-mono font-bold text-amber-400">
                {(result.replay_score * 100).toFixed(1)}%
              </span>
            </div>
            <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-800">
              <div
                className="h-full bg-amber-500 transition-all duration-500"
                style={{ width: `${Math.max(2, result.replay_score * 100)}%` }}
              />
            </div>
          </div>

          {/* Overall Risk Signal */}
          <div className="space-y-1">
            <div className="flex items-center justify-between text-xs">
              <span className="text-slate-300 font-medium">Overall Risk</span>
              <span className={`font-mono font-bold ${result.status === 'SAFE' ? 'text-emerald-400' : 'text-rose-400'}`}>
                {(result.risk_score * 100).toFixed(1)}%
              </span>
            </div>
            <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-800">
              <div
                className={`h-full transition-all duration-500 ${result.status === 'SAFE' ? 'bg-emerald-500' : 'bg-rose-500'}`}
                style={{ width: `${Math.max(2, result.risk_score * 100)}%` }}
              />
            </div>
          </div>

        </div>
      </div>

      {/* 3. "WHY THIS VERDICT?" Section */}
      <div className="p-5 bg-slate-950/80 rounded-xl border border-slate-800 space-y-3">
        <h4 className="text-xs uppercase font-extrabold tracking-widest text-slate-300 flex items-center space-x-2">
          <AlertCircle className="w-4 h-4 text-cyan-400" />
          <span>WHY THIS VERDICT?</span>
        </h4>

        <div className="space-y-2">
          {result.reasons.map((reason, idx) => (
            <div key={idx} className="flex items-start space-x-2.5 text-xs text-slate-200">
              {result.status === 'SAFE' ? (
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
              ) : (
                <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
              )}
              <span>{reason}</span>
            </div>
          ))}
        </div>

        {/* Structured Evidence (if present) */}
        {result.evidence && result.evidence.length > 0 && (
          <div className="pt-3 border-t border-slate-900 space-y-2">
            <span className="text-[10px] uppercase font-bold text-slate-400 tracking-widest block">EVIDENCE</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {result.evidence.map((item, idx) => (
                <div key={idx} className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-[11px] space-y-1 font-mono">
                  <div className="flex items-center justify-between text-slate-300 font-bold">
                    <span>{item.code || item.category || 'SYNTHETIC VOICE'}</span>
                    <span className="text-cyan-400">
                      Observed: {item.observed_value !== undefined ? item.observed_value.toFixed(4) : 'N/A'}
                    </span>
                  </div>
                  {item.threshold !== undefined && (
                    <div className="text-slate-500 text-[10px]">Threshold: {item.threshold.toFixed(2)}</div>
                  )}
                  {item.message && <p className="text-slate-400 pt-0.5 font-sans">{item.message}</p>}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* 4. Collapsible Technical Analysis */}
      <div>
        <button
          onClick={() => setShowTechnical(!showTechnical)}
          className="w-full flex items-center justify-between p-3.5 rounded-xl bg-slate-950 hover:bg-slate-900 border border-slate-800 text-xs font-semibold text-slate-300 transition-all"
        >
          <div className="flex items-center space-x-2">
            <FileText className="w-4 h-4 text-cyan-400" />
            <span>TECHNICAL ANALYSIS ▾</span>
          </div>
          {showTechnical ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
        </button>

        {showTechnical && (
          <div className="mt-3 p-5 rounded-xl bg-slate-950 border border-slate-800 text-xs space-y-4 font-mono">
            
            {/* Technical Pipeline Checklist */}
            <div>
              <span className="text-slate-400 uppercase tracking-widest text-[10px] block mb-2 font-bold">
                Forensic Pipeline Execution
              </span>
              <div className="space-y-1.5 text-[11px]">
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>1. Audio Payload Received</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>2. Audio Normalization</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>3. Feature Extraction</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>4. Neural Anti-Spoofing</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>5. Acoustic Replay DSP</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-slate-900 text-emerald-400">
                  <span>6. Risk Assessment</span>
                  <span>✓</span>
                </div>
                <div className="flex items-center justify-between py-1 text-cyan-300 font-bold">
                  <span>7. Final Verdict ({result.verdict || result.status})</span>
                  <span>✓</span>
                </div>
              </div>
            </div>

            {/* Actual Backend Timeline Timings if present */}
            {result.forensic_timeline && result.forensic_timeline.length > 0 && (
              <div>
                <span className="text-slate-400 uppercase tracking-widest text-[10px] block mb-2 font-bold">
                  Backend Execution Timings
                </span>
                <div className="space-y-1 text-[11px]">
                  {result.forensic_timeline.map((stage, idx) => (
                    <div key={idx} className="flex items-center justify-between py-1 border-b border-slate-900 text-slate-300">
                      <span>{stage.stage_id}. {stage.stage_name}</span>
                      <span className="text-slate-400">{stage.execution_time_ms.toFixed(2)} ms</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="text-[10px] text-slate-500 pt-2 border-t border-slate-900">
              Evaluator Version: {result.evaluator_version || 'risk_engine_v1.0'} | Model Architecture: ResNet 2D CNN (80 Log-Mel + 20 LFCC)
            </div>
          </div>
        )}
      </div>

      {/* 5. Result Actions */}
      <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-800">
        {onReset && (
          <button
            onClick={onReset}
            className="flex items-center space-x-2 px-5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-all"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>ANALYZE ANOTHER SAMPLE</span>
          </button>
        )}

        <button
          onClick={() => setShowTechnical(!showTechnical)}
          className="flex items-center space-x-2 px-5 py-2.5 rounded-xl bg-slate-950 hover:bg-slate-900 text-slate-300 border border-slate-800 text-xs font-semibold transition-all"
        >
          <FileText className="w-3.5 h-3.5 text-cyan-400" />
          <span>TECHNICAL ANALYSIS</span>
        </button>
      </div>

    </div>
  );
};
